name: inertia
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: ">=3.3.3 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flex_color_scheme: ^7.3.1
  flutter_bloc: ^8.1.5
  dio: ^5.4.3+1
  get_it: ^7.6.7
  bloc: ^8.1.4
  go_router: ^13.2.4
  meta: ^1.11.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  auto_size_text: ^3.0.0
  icons_plus: ^5.0.0
  animate_do: ^3.3.4
  equatable: ^2.0.5
  flutter_riverpod: ^2.4.6
  riverpod_annotation: ^2.3.5
  path_provider: ^2.1.4
  avatar_generator: ^0.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  isar_generator: ^3.1.0+1
  build_runner: any
  riverpod_generator:

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/noto/NotoSans-Regular.ttf

  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
